version: '3'

services:

  api:
    container_name: api
    build:
      context: ./api
    volumes:
      - .:/code
      - ./logs:/var/log
    env_file:
      - ./api/api.env
    ports:
      - 5000:5000
    depends_on:
      - redis
      - group_assignments
    restart: always

  group_assignments:
    container_name: ga
    build:
      context: ./group_assignments
    volumes:
      - .:/code
      - ./logs:/var/log
    env_file:
      - ./group_assignments/group_assignments.env
    ports:
      - 8000:8000
    restart: always

  load_testing:
    container_name: lt
    build:
      context: ./load_testing
    volumes:
      - .:/code
      - ./logs:/var/log
    env_file:
      - ./load_testing/load_testing.env
    ports:
      - 8089:8089
    depends_on:
      - api
      - group_assignments
    restart: always

  redis:
    container_name: redis
    image: redis:5.0.1
    ports:
      - 6379:6379
    restart: always
