version: '3'

services:

  api:
    container_name: api
    build:
      context: ./api
    volumes:
      - .:/code
      - ./logs/api:/var/log/api
    env_file:
      - ./api/api.env
    ports:
      - 5000:5000
    depends_on:
      - redis
    restart: always

  load_testing:
    container_name: lt
    build:
      context: ./load_testing
    volumes:
      - .:/code
      - ./logs/lt:/var/log
    env_file:
      - ./load_testing/load_testing.env
    ports:
      - 8089:8089
    depends_on:
      - api
    restart: always

  redis:
    container_name: redis
    image: redis:5.0.1
    ports:
      - 6379:6379
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.5.4
    ports:
      - 9200:9200
    restart: always

  cerebro:
    container_name: cerebro
    image: yannart/cerebro:latest
    ports:
      - 9000:9000
    depends_on:
      - elasticsearch
    restart: always
  
  logstash:
    container_name: logstash
    image: logstash:6.5.4
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/ml-logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./logstash/logs-template.json:/etc/logstash/templates/logs-template.json
      - ./logs/api:/var/log/api
    depends_on:
      - elasticsearch
    restart: always

  kibana:
    container_name: kibana
    image: kibana:6.5.4
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: always
